[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
computercraft_simulator = { path = "crates/computercraft_simulator" }
minecraft = { path = "crates/minecraft" }

mlua = "0.9"
pretty_assertions = "1.4.1"
thiserror = "1.0"
